version: "3.7"

services:
    object-detection:
        build: 
            context: .
            args:                                                                      
                ARCHITECTURE: "1.15.0"
        image: object-detection:latest
        container_name: object-detection
        expose:
            - 8080
        environment:
            - MODEL_SERVER_WORKERS=1
        ports:
            - 8080:8080
        volumes:
            - ./model:/opt/ml/model
            - ./cache:/opt/ml/cache
        command: serve
