version: "3.7"

services:
    doodl:
        build: 
            context: .
            args:                                                                      
                ARCHITECTURE: "1.15.0"
        image: doodl:latest
        container_name: doodl
        expose:
            - 8080
        environment:
            - MODEL_SERVER_WORKERS=1
        ports:
            - 8080:8080
        volumes:
            - ./model:/opt/ml/model
            - ./cache:/opt/ml/cache
        command: serve
